name: Build for Mac Native

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-mac-native:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
         setup-python: false
         py7zrversion: '==0.20.*'
      
    - run: ./scripts/build_macos_native.sh
      name: build-for-mac

    - uses: actions/upload-artifact@master
      with:
         name: tsMuxer
         path: build/bin/mac.zip
      name: upload-artefact
